
const SEL = {
    tvLegendIndicatorItem: 'div[data-name="legend"] div[class^="sourcesWrapper"] div[class^="sources"] div[data-name="legend-source-item"]',
    tvLegendIndicatorItemTitle: 'div[data-name="legend-source-title"]',
    tvDialogRoot: '#overlap-manager-root',
    indicatorTitle: '#overlap-manager-root div[data-name="indicator-properties-dialog"] div[class^="title"]',
    tabInput: 'div[data-name="indicator-properties-dialog"] div[data-value="inputs"]',
    tabInputActive: 'div[data-name="indicator-properties-dialog"] div[class*="active"][data-value="inputs"]',
    tabProperties: 'div[data-name="indicator-properties-dialog"] div[data-value="properties"]',
    ticker: '#header-toolbar-symbol-search > div[class*="text-"]',
    timeFrame: '#header-toolbar-intervals div[data-role^="button"]',
    timeFrameActive: '#header-toolbar-intervals div[data-role^="button"][class*="isActive"]',
    indicatorScroll: 'div[data-name="indicator-properties-dialog"] div[class^="scrollable-"]',
    indicatorProperty: 'div[data-name="indicator-properties-dialog"] div[class^="content-"] div[class^="cell-"]',
    okBtn: 'div[data-name="indicator-properties-dialog"] div[class^="footer-"] button[name="submit"]',
    cancelBtn: 'div[data-name="indicator-properties-dialog"] span[data-name="close"][data-role="button"]',
    strategyTesterTab: '#footer-chart-panel div[data-name="backtesting"]',
    strategyTesterTabActive: '#footer-chart-panel div[data-name="backtesting"][data-active="true"]',
    strategyCaption: '#bottom-area div.backtesting-head-wrapper .strategy-select .caption',
    strategyCaptionNew: '#select-backtesting-strategy',
    strategyDialogParam: '#bottom-area div.backtesting-head-wrapper .js-backtesting-open-format-dialog',
    strategyDialogParamNew: '#bottom-area div[class^="backtesting_head_wrapper"]  div[class^="setting"]  > button:nth-child(2)',
    strategySummary: '#bottom-area div.backtesting-head-wrapper .backtesting-select-wrapper > ul >li:nth-child(2)',
    strategySummaryNew: '#bottom-area div[class^="backtesting_head_wrapper"] div[class^="tabSwitcher"] > button:nth-child(2)',
    strategySummaryActive: '#bottom-area div.backtesting-head-wrapper .backtesting-select-wrapper > ul >li.active:nth-child(2)',
    strategySummaryActiveNew: '#bottom-area div[class^="backtesting_head_wrapper"] div[class^="tabSwitcher"] > button[class*="activeTab"]:nth-child(2) ',
    strategyReport: '#bottom-area div.backtesting-content-wrapper > div.reports-content',
    strategyReportInProcess: '#bottom-area div.backtesting-content-wrapper > div.reports-content.fade',
    strategyReportReady: '#bottom-area div.backtesting-content-wrapper > div:not(.fade).reports-content',
    strategyReportError: '#bottom-area div.backtesting-content-wrapper > div.reports-content.report-error',
    strategyReportHeader: '#bottom-area div.backtesting-content-wrapper .report-data thead > tr > td',
    strategyReportRow: '#bottom-area div.backtesting-content-wrapper .report-data tbody > tr',
    strategyListOptions: 'div[role="listbox"] div[data-name="menu-inner"] div[role="option"] div[class^="label-"]',
    strategyDefaultElement: '#study-defaults-manager',
    strategyImportExport: '#iondvImportExport'
}